### ISSUE TITLE
django_db_geventpool.backends.postgresql_psycopg3 not available

### ISSUE THREAD

**Issue by ShabirK21** [jneight/django-db-geventpool#82]
I've updated to django-db-geventpool 4.0.3 and installed psycopg[binary] but when i set ENGINE to django_db_geventpool.backends.postgresql_psycopg3, i get "django.core.exceptions.ImproperlyConfigured: 'django_db_geventpool.backends.postgresql_psycopg3' isn't an available database backend or couldn't be imported. Check the above exception. To use one of the built-in backends, use 'django.db.backends.XXX'"

Im using:
Django 4.2.13
Psycopg 3.1.19
Django-db-geventpool 4.0.3

**Comment by yokotoka** [comment]
Same problem
It's not working like in documentation

```
DATABASES = {
    "default": {
        "ENGINE": "django_db_geventpool.backends.postgresql_psycopg3",
        "NAME": POSTGRES_DB,
        "USER": POSTGRES_USER,
        "PASSWORD": POSTGRES_PASSWORD,
        "HOST": POSTGRES_HOST,
        "PORT": POSTGRES_PORT,
        "ATOMIC_REQUESTS": False,
        "CONN_MAX_AGE": 0,
        "OPTIONS": {"MAX_CONNS": 20, "REUSE_CONNS": 10},
    }
}
```

```
django.core.exceptions.ImproperlyConfigured: 'django_db_geventpool.backends.postgresql_psycopg3' isn't an available database backend or couldn't be imported. Check the above exception. To use one of the built-in backends, use 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
```

**Comment by yokotoka** [comment]
It looks like pypi version not contain postgresql_psycopg3 module

![image](https://github.com/jneight/django-db-geventpool/assets/1014859/7ddcdf9a-252a-4e76-b953-cb91f8a2225e)

**Comment by yokotoka** [comment]
@jneight

**Comment by JustIceQAQ** [comment]
Hi, I am experiencing the same issue.

Here are the versions I’m using:
- django==4.2.17
- psycopg[binary]==3.2.3
- django-db-geventpool==4.0.7

My settings.py configuration:
```python
import environ
env = environ.Env()

DATABASES["default"] = env.db("DATABASE_URL")  # noqa F405
DATABASES["default"]["ATOMIC_REQUESTS"] = False  # noqa F405
DATABASES["default"]["CONN_MAX_AGE"] = env.int("CONN_MAX_AGE", default=0)  # noqa F405
if "OPTIONS" not in DATABASES["default"]:  # noqa F405
    DATABASES["default"]["OPTIONS"] = {}  # noqa F405
DATABASES["default"]["ENGINE"] = "django_db_geventpool.backends.postgresql_psycopg3"  # noqa F405
DATABASES["default"]["OPTIONS"]["MAX_CONNS"] = env.int("OPTIONS_MAX_CONNS", default=20)  # noqa F405
DATABASES["default"]["OPTIONS"]["REUSE_CONNS"] = env.int(  # noqa F405
    "OPTIONS_REUSE_CONNS", default=20
)  # noqa F405
```

Additionally, I noticed the PyPI documentation indicates the postgresql_psycopg3 module is available for django-db-geventpool. However, the error persists.
Here's a related screenshot from PyPI:
![image](https://github.com/user-attachments/assets/e606b792-7ef3-4035-8d2a-9068837a8bf0)

Does this setup look correct? Could the issue be caused by a configuration mismatch, or is there a known bug with the library versions I’m using?

Thank you for your help!
